### PR TITLE
Show es5

### PR DESCRIPTION
**Pull request by tessalt**

### CODE REVIEW

**Comment by tessalt** [comment]
integrated with theme picker, added some style improvements to output panel and then was a jerk and changed your buttons to be more google-y because I didn't like them. 

But look how nice and at home it looks with the light theme: 

screen shot 2015-02-11 at 11 16 30 pm

BUT if you hate it you can just revert  a302d24

**Comment by tessalt** [comment]
Going to look into making the panel resizeable but it might be hard/gross so I think 30% width is good enough for now

**Comment by tessalt** [comment]
draggy2

wheee

**Comment by richgilbank** [comment]
Full of win! Thanks for this :).

**Pull request merged**
